### ISSUE TITLE
Scheduled tasks not sends CC, BCC

### ISSUE THREAD

**Issue by maiskiykot** [stackkit/laravel-database-emails#35]
I tried use scheduled emails from your package but 1) Not work your command class - SendEmailsCommand, 2) Not work sending CC BCC - only recipient. How I can fix it? Thank you!

**Comment by marickvantuil** [comment]
I can't help you with this little information. Do you have any errors you're getting, or explain in more detail what exactly is not working as expected?

**Comment by maiskiykot** [comment]
Thanks for your answer!
1) I added scheduled email in base + 20 min. Is correct. I added command "email:send" to Kernel.php. Nothing! Emails not sends.
2) If I use artisan schedule:test - email sends. But email have three recipients - To, CC, BCC. In log fixed only To. I think must have three recipients. Is right?

**Comment by marickvantuil** [comment]
Hm, I can't reproduce either issues.

1. Maybe a stupid assumption, but do you have the Laravel `schedule:run` command configured as a cronjob?
2. It should definitely appear in cc and bcc, like this;

<img width="749" alt="Screenshot 2021-07-18 at 16 13 25" src="https://user-images.githubusercontent.com/647007/126070568-92c6093f-6a8a-400b-922c-fca202e59766.png">

<img width="645" alt="Screenshot 2021-07-18 at 16 12 17" src="https://user-images.githubusercontent.com/647007/126070573-4820310a-b2fc-4164-911f-11deb7e92888.png">

What PHP and Laravel version are you on? Can you share more info how you are calling the functions? Otherwise I have no idea what is going wrong.

**Comment by maiskiykot** [comment]
Command                                 | Interval  | Description | Next Due                   |
+-----------------------------------------+-----------+-------------+----------------------------+
|                                         | 0 0 * * * |             | 2021-07-19 00:00:00 +00:00 |
| '/usr/bin/php7.4' 'artisan' email:send  | * * * * * |             | 2021-07-18 15:20:00 +00:00 |
| '/usr/bin/php7.4' 'artisan' snooze:send | * * * * * |             | 2021-07-18 15:20:00 +00:00

**Comment by maiskiykot** [comment]
I asked about scheduled emails. You indicate result for  send() not later()
